#facebook:
#    app:
#        id: 1084911261562762
#        secret: 81a324fdbc4cade1ee25523c7bff58b3
#    scope: public_profile,email
#    security:
#      oauth2:
#        client:
#          clientId: 233668646673605
#          clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
#          accessTokenUri: https://graph.facebook.com/oauth/access_token
#          userAuthorizationUri: https://www.facebook.com/dialog/oauth
#          tokenName: oauth_token
#          authenticationScheme: query
#          clientAuthenticationScheme: form
#        resource:
#          userInfoUri: https://graph.facebook.com/me
facebook:
  client:
    clientId: 472324530036850
    clientSecret: 8c2a9f70f03f870a6523f6312f28af45
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
#    scope: public_profile,email
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me?fields=id,name,email,gender,photos
google:
    client:
        accessTokenUri: https://www.googleapis.com/oauth2/v4/token
        clientAuthenticationScheme: form
        clientId: 1075144207253-0vdtldhpojqi4hkj1bumliftsdg33963.apps.googleusercontent.com
        clientSecret: L9XacHhUTlwXZc5BzaiQISAI
        scope: openid,email,profile
        userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    resource:
        preferTokenInfo: true
        userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
#        twitter:
#            client:
#                accessTokenUri: https://www.googleapis.com/oauth2/v4/token
#                clientAuthenticationScheme: form
#                clientId: 1075144207253-0vdtldhpojqi4hkj1bumliftsdg33963.apps.googleusercontent.com
#                clientSecret: L9XacHhUTlwXZc5BzaiQISAI
#                scope: openid,email,profile
#                userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
#            resource:
#                preferTokenInfo: true
#                userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
spring:
    datasource:
        password: 1111
        url: jdbc:mysql://localhost:3306/a_demo?serverTimezone=UTC
        username: root
    jpa:
        hibernate:
            ddl-auto: update
upload:
    path: g:/Java/1_1_Kursovoy/advt/src/uploads/
