#facebook:
#    app:
#        id: 1084911261562762
#        secret: 81a324fdbc4cade1ee25523c7bff58b3
#    scope: public_profile,email
#    security:
#      oauth2:
#        client:
#          clientId: 233668646673605
#          clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
#          accessTokenUri: https://graph.facebook.com/oauth/access_token
#          userAuthorizationUri: https://www.facebook.com/dialog/oauth
#          tokenName: oauth_token
#          authenticationScheme: query
#          clientAuthenticationScheme: form
#        resource:
#          userInfoUri: https://graph.facebook.com/me
facebook:
  client:
    clientId: 472324530036850
    clientSecret: ${facebookSecret}
#    8c2a9f70f03f870a6523f6312f28af45
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
#    scope: public_profile,email
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me?fields=id,name,email,gender,photos
google:
    client:
        accessTokenUri: https://www.googleapis.com/oauth2/v4/token
        clientAuthenticationScheme: form
        clientId: 1075144207253-0vdtldhpojqi4hkj1bumliftsdg33963.apps.googleusercontent.com
        clientSecret: ${googlSecret}
#        L9XacHhUTlwXZc5BzaiQISAI
        scope: openid,email,profile
        userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    resource:
        preferTokenInfo: true
        userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
#        twitter:
#            client:
#                accessTokenUri: https://www.googleapis.com/oauth2/v4/token
#                clientAuthenticationScheme: form
#                clientId: 1075144207253-0vdtldhpojqi4hkj1bumliftsdg33963.apps.googleusercontent.com
#                clientSecret: L9XacHhUTlwXZc5BzaiQISAI
#                scope: openid,email,profile
#                userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
#            resource:
#                preferTokenInfo: true
#                userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
#mail:
#    debug: true
#
spring:
    datasource:
        password: 1111
        url: jdbc:mysql://localhost:3306/a_demo?serverTimezone=UTC
        username: root
    jpa:
        generate-ddl: true
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
    session:
        jdbc:
            initialize-schema: always
            schema: classpath:session_tables.sql
            table-name: SPRING_SESSION

#    mail:
#
#         host: smtp.gmail.com
#         username: henadiyv@gmail.com
#         password: $84726751vge
#         port: 587
#         protocol: smtps
#         properties:
#                    mail:
#                      smtp:
#                        auth: true
#                        starttls:
#                              enable: true
#                              required: true
#                        ssl:
#                             enable: true


#         scheduler:
#                  persistence:
#                            enabled: false
#                             redis:
#                                  embedded: false
#                                  enabled: false

#                     timeout: 5000
#                     writetimeout: 5000


#    mail:
#            host: smtp.gmail.com
#            username: henadiyvognev@gmail.com
#            password: 84726751Vge
#            port: 587 465
#            protocol: smtp
#            properties:
#                mail:
#                    smtp:
#                        auth: true
#                        starttls:
#                            enable: true
#
#
#

#                        connectiontimeout : 5000
#                        timeout : 5000
#                        writetimeout : 5000

upload:
    path: g:/Java/1_1_Kursovoy/lost-and-found/src/uploads/
uploadUs:
    path: g:/Java/1_1_Kursovoy/lost-and-found/src/users/
project:
    path: g:/Java/1_1_Kursovoy/lost-and-found/src/tutorial-project/
hostname:
        localhost:8080
#upload:
#    path: /home/u109789/uploads/
#uploadUs:
#    path: /home/u109789/users/
#project:
#    path: /home/u109789 /tutorial-project/
#
#hostname: 109789.prohoster.biz
#cnixxsimmqrcfwpr
#84726751vge
#vognevhenadij@gmail.com

#$84726751vge
#henadiyv@gmail.com

#84726751Vge
#henadiyvognev@gmail.com